[campaign]
id = "two_brothers"
name = "A Tale of Two Brothers"
faction_0 = "loyalists"
faction_1 = "undead"
gold_carry_percent = 40
early_finish_bonus = 3

[[scenarios]]
board = "rooting_out_a_mage/board.toml"
units = "rooting_out_a_mage/units.toml"
preset_units = true

[[scenarios]]
board = "the_chase/board.toml"
units = "the_chase/units.toml"
preset_units = true

[[scenarios]]
board = "guarded_castle/board.toml"
units = "guarded_castle/units.toml"
preset_units = true

[[scenarios]]
board = "return_to_village/board.toml"
units = "return_to_village/units.toml"
preset_units = true
